import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import localFont from "next/font/local";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppinsLight = Poppins({
  weight: "300",
  variable: "--font-poppins-light",
  subsets: ["latin"],
});

const ivyModeSemiBold = localFont({
  src: "../fonts/ivy-mode-semi-bold.woff2",
  variable: "--font-ivy-mode-semi-bold",
  display: "swap",
});

const ivyModeRegular = localFont({
  src: "../fonts/IvyMode-Regular.ttf",
  variable: "--font-ivy-mode-regular",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-arp="">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${poppinsLight.variable} ${ivyModeSemiBold.variable} ${ivyModeRegular.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
